// Module included in the following assemblies:
//
// *deployment/deployment.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc-rhcl-oidc-verify_{context}"]
= Verifying an OIDC AuthPolicy custom resource

[role="_abstract"]
You can verify that your OIDC authentication layer is working with two steps.

.Prerequisites

* You installed {prodname} on one or more clusters.
* You installed the {oc-first}.
* You have write access to the {ocp} namespaces you need to work with.
* You have access to external or on-premise DNS.
* You created a `Gateway` object.
* You created an `HTTPRoute` or `GRPCRoute` object.
* You created an `AuthPolicy` CR.
* You configured got a token from your OIDC provider.

.Procedure

. Send a GET request to your API while attaching the JSON Web Token (JWT) that you got from {keycloak} inside the `Authorization` header by running the following command:
+
[source,terminal]
----
$ curl -H "Authorization: Bearer $ACCESS_TOKEN" http://talker-api.127.0.0.1.nip.io:8000/hello
----
+
.Example output
[source,text]
----
HTTP/1.1 200 OK
----

. Send the exact same request to your API, but omit the `Authorization` header by running the following command:
+
[source,terminal]
----
$ curl http://talker-api.127.0.0.1.nip.io:8000/hello -i
----
+
.Example output
[source,text]
----
HTTP/1.1 401 Unauthorized
x-ext-auth-reason: credential not found
----
